# Site settings
title: Microdust
header-img: "img/autumn2.jpg"
tagline: "吉光片羽"
description: "在遙遠的地方 一切虔誠終必相遇"
baseurl: ""
url: "http://lan-cyl.github.io"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "yongle.cai"
  email: caiyongle91@gmail.com
  bio: "好好学习 天天向上"

# Data
# gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: Lancyl
twitter_username: Lancyl
github_username: lan-cyl
facebook_username: Lancyl
weibo_username: Lancyl
zhihu_username: Lancyl

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lancyl"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : Lancyl
  disqus :
      short_name : Lancyl

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
