# Site settings
title: lan_cyl's blog
header-img: "img/home-bg-01.jpg"
tagline: "吉光片羽"
description: "源码之前 了无秘密"
baseurl: ""
#url: "http://azeril.me"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "lan_cyl"
  email: caiyongle91@gmail.com
  bio: "源码之前 了无秘密"

# Data
gavatar: img/my.png
favicon: img/favicon.ico

#douban_username: Azeril
#twitter_username: Azeril_Lapland
github_username: lan-cyl
#facebook_username: Azeril_Lapland
#weibo_username: Azeril
#zhihu_username: lan_cyl

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "lan_cyl"
      header-img: "img/post-bg-01.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : lan-cyl
  disqus :
      short_name : lan-cyl

# Analytics and webmaster tools stuff goes here
#google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
